### ISSUE TITLE
More IOCs from other sources.

### ISSUE THREAD

**Issue by ideaengine007** [parthdmaniar/coronavirus-covid-19-SARS-CoV-2-IoCs#1]
Some more IOCs to look into, Sir. 

- https://www.anomali.com/learn/covid19
- https://github.com/sophoslabs/covid-iocs/
- https://github.com/carbonblack/tau-tools/tree/master/threat_hunting/IOCs

**Comment by parthdmaniar** [comment]
Thank you very much. Let me verify and put them.

**Comment by parthdmaniar** [comment]
Incorporated. Thank you very much. As all the information here is under MIT. You may fork it and push an update, I will merge it. Thank you once again.
