### ISSUE TITLE
Please whitelist covid-19-sounds.org

### ISSUE THREAD

**Issue by sdimi** [parthdmaniar/coronavirus-covid-19-SARS-CoV-2-IoCs#10]
Hi,

I am the developer of http://covid-19-sounds.org/, a research project from the University of Cambridge.

Please whitelist our project, we are collecting valuable cough and breathing data to develop models in order to detect covid19. 

Proof of validity: the university has officially covered us here https://www.cam.ac.uk/research/news/new-app-collects-the-sounds-of-covid-19

**Comment by parthdmaniar** [comment]
Done. This was ingested due to US Government advisory - https://www.us-cert.gov/ncas/alerts/aa20-099a. I have removed it in update 6.1.

Thank you and sorry.

**Comment by sdimi** [comment]
Thank you, Parth! We are aware of the US Government advisory and we have contacted them. Do you know of better ways to reach them beyond their public email?

**Comment by parthdmaniar** [comment]
I have already sent email to my contact with the US-CERT. I will follow up over the weekend. Thank you and I wish you, your loved ones and your team good health.
