### ISSUE TITLE
Remove www.google.com and www.twitter.com

### ISSUE THREAD

**Issue by pwo** [parthdmaniar/coronavirus-covid-19-SARS-CoV-2-IoCs#12]
www.google.com and www.twitter.com came with cabc3d9a3816e87ef272a35eb03dd09af61e61ad in URLs

**Comment by parthdmaniar** [comment]
Thank you for bringing this to my notice. I have pushed version 10.0 which removes these entries.

I am running a bash script to remove Alexa top million domains from the list (if at all present).

Thank you for bringing this to my notice.
