### ISSUE TITLE
Please whitelist coronavirusdatamap.com and californiacoronavirus.org! 

### ISSUE THREAD

**Issue by nchilada** [parthdmaniar/coronavirus-covid-19-SARS-CoV-2-IoCs#2]
Hi there, coronavirusdatamap.com and californiacoronavirus.org appear to be trustworthy websites owned by @embreinhardt, but they're currently blacklisted. Could you please find a way to whitelist them? Let me know if I can help with that!

**Comment by embreinhardt** [comment]
I'm the developer behind these sites, please let me know if you have any questions about them in order to get them whitelisted! Both are entirely based on vetted historical data from the New York Times, and San Francisco Chronicle

**Comment by parthdmaniar** [comment]
Done, thank you and sorry. These were in list by domain tools which is clearly marked as having legitimate websites too. I will retire the list in next 2 days once my script to find URL reputation finishes. 

Wishing you and your loved ones good health. 

Thank you.
