### ISSUE TITLE
Please whitelist covid19map.us

### ISSUE THREAD

**Issue by freedmand** [parthdmaniar/coronavirus-covid-19-SARS-CoV-2-IoCs#7]
Hi there,

I am the developer of covid19map.us, an informational map I built using public data from USAFacts. The website is a static page hosted by Netlify that is open source (https://github.com/freedmand/covid19map.us) – there are no ads, tracking, phishing, or any other malware. Please let me know if I can provide any further information.

**Comment by parthdmaniar** [comment]
Hi I am reviewing this now. There is no need for further proof. Thank you.

**Comment by parthdmaniar** [comment]
Hi, please be advised that I am removing it from my list. However, I ingested this based on US Govt CERT Alert (AA20-099A). You will need to contact them to have it removed - https://www.us-cert.gov/ncas/alerts/aa20-099a && direct link to the IoC file: https://www.us-cert.gov/sites/default/files/publications/AA20-099A_WHITE.csv.

Pushing emergency update to have this removed now. Version: 4.5.1

**Comment by freedmand** [comment]
Thanks @parthdmaniar – I've contacted them as well. Appreciate the quick turnaround!

**Comment by parthdmaniar** [comment]
No worries, wishing & your loved ones good health.
