### ISSUE TITLE
Please whitelist coronavirus3d.org

### ISSUE THREAD

**Issue by sanshu** [parthdmaniar/coronavirus-covid-19-SARS-CoV-2-IoCs#8]
Hello, 
I'm the developer of this website, it's a scientific tool based on public data. Could you please remove it from your list. Let me know if you need any additional information.

**Comment by parthdmaniar** [comment]
No further information required. I got this from US-CERT advisory : https://www.us-cert.gov/ncas/alerts/aa20-099a . Please contact them to have it removed from their list. 

This will be removed in update 5.2.1

**Comment by parthdmaniar** [comment]
Update pushed. Closing issue.

**Comment by sanshu** [comment]
Thank you!
