### ISSUE TITLE
License

### ISSUE THREAD

**Issue by andrew134598** [parthdmaniar/coronavirus-covid-19-SARS-CoV-2-IoCs#9]
Please let me know if could we use your feed in our security product for free?

**Comment by parthdmaniar** [comment]
Hi Andrew, could you know the name of the security product please?

**Comment by andrew134598** [comment]
FlowControl - this a tool to monitor flows

**Comment by parthdmaniar** [comment]
Please go ahead. I wish you and everyone in your company good health. If possible please donate towards research of kidney related diseases and mention name of my parents (Saroj Maniar or Dilip Maniar) somewhere for using this. None of this is mandatory. 

Please go ahead and use it without any constraints. 

Thank you.

**Comment by parthdmaniar** [comment]
Also FlowControl is a product or company's name? Just for my records. Thank you.

**Comment by andrew134598** [comment]
Thanks a lot. Passus. Do you update this feed regularly?

**Comment by parthdmaniar** [comment]
Daily.

**Comment by andrew134598** [comment]
Great. Thank as a lot.

**Comment by parthdmaniar** [comment]
Also my wife's name: Akansha Maniar as she has been my strongest support :) Thank you :)
